### ISSUE TITLE
Plugin is not compatible with Zeek 5.2.0

### ISSUE THREAD

**Issue by awelzel** [corelight/bro-quic#3]
Attempting to compile on Zeek 5.2.0 results in the following error:

```
make: [Makefile:12: build-it] Error 1 (ignored)                                                                                                                
In file included from /opt/zeek/var/lib/zkg/clones/package/zeek-quic/src/GQUIC.cc:1:
/opt/zeek/var/lib/zkg/clones/package/zeek-quic/src/GQUIC.h:6:10: fatal error: zeek/analyzer/protocol/udp/UDP.h: No such file or directory                      
    6 | #include "zeek/analyzer/protocol/udp/UDP.h"                            
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                            
compilation terminated.                                                        
make[3]: *** [CMakeFiles/Corelight-GQUIC.linux-x86_64.dir/build.make:148: CMakeFiles/Corelight-GQUIC.linux-x86_64.dir/src/GQUIC.cc.o] Error 1                  
make[2]: *** [CMakeFiles/Makefile2:278: CMakeFiles/Corelight-GQUIC.linux-x86_64.dir/all] Error 2                                                               
make[1]: *** [Makefile:182: all] Error 2                                                                                                                       
make: *** [Makefile:13: build-it] Error 2
```
